global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderers"
    static_configs:
      - targets: ["orderer0.example.com:9443","orderer1.example.com:9444","orderer2.example.com:9445"]
  - job_name: "Org1 Peers"
    static_configs:
      - targets: ["peer0.org1.example.com:9440"]
  - job_name: "Org2 Peers"
    static_configs:
      - targets: ["peer0.org2.example.com:9441"]
  - job_name: "Org3 Peers"
    static_configs:
      - targets: ["peer0.org3.example.com:9442"]