global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer0"
    static_configs:
      - targets: ["orderer0.example.com:9443"]
  - job_name: "orderer1"
    static_configs:
      - targets: ["orderer1.example.com:9444"]
  - job_name: "peer0_org1"
    static_configs:
      - targets: ["peer0.org1.example.com:9440"]
  - job_name: "peer0_org2"
    static_configs:
      - targets: ["peer0.org2.example.com:9441"]
  - job_name: "peer0_org3"
    static_configs:
      - targets: ["peer0.org3.example.com:9442"]
