# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

networks:
  test:
    name: test
    external: true

services:

  couchdb0:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    image: couchdb:3.1.1
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    volumes:
      - ../production/couchdb/data0:/opt/couchdb/data
    ports:
      - "5984:5984"
    networks:
      test:
        aliases:
        - couchdb0
  
  couchdb1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    image: couchdb:3.1.1
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    volumes:
      - ../production/couchdb/data1:/opt/couchdb/data
    ports:
      - "6984:5984"
    networks:
      test:
        aliases:
        - couchdb1

  couchdb2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    image: couchdb:3.1.1
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    volumes:
      - ../production/couchdb/data2:/opt/couchdb/data
    ports:
      - "7984:5984"
    networks:
      test:
        aliases:
        - couchdb2